send_message:
  name: 发送微信消息
  description: 通过 Bemfa API 发送微信消息通知
  fields:
    device_entity:
      name: 消息来源实体
      description: 从系统中选择一个实体（如传感器、摄像头等）
      required: true
      selector:
        entity:
          domain:
            - binary_sensor
            - sensor
            - camera
            - device_tracker
          multiple: false

    message:
      name: 消息内容
      description: 要发送的消息文本内容
      required: true
      example: "检测到异常"
      selector:
        text:
          multiline: true

    group:
      name: 消息分组（可选）
      description: 用于分组接收消息
      required: false
      example: "HomeSecurity"
      selector:
        text:
          multiline: false

    url:
      name: 跳转链接（可选）
      description: 点击消息后跳转的链接地址
      required: false
      example: "https://example.com"
      selector:
        text:
          multiline: false
