send_message:
  name: 发送微信消息
  description: 通过巴法云 API 发送微信内容
  fields:
    device_entity:
      name: 实体
      description: 用于展示状态的实体（可选）
      required: true
      selector:
        entity: {}
    message:
      name: 消息
      description: 要发送的附加信息
      required: true
      selector:
        text:
          multiline: true
    group:
      name: 分组（可选）
      description: 微信推送的分组标识
      required: false
      default: "default"
      selector:
        text:
          multiline: false
    url:
      name: 跳转链接（可选）
      description: 微信消息跳转的 URL
      required: false
      default: ""
      selector:
        text:
          multiline: false